modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="Apache License 2.0"
issueTrackerURL="https://github.com/satxm/mcwifipnp/issues"
clientSideOnly=false

[[mods]]
modId="mcwifipnp"
version="${mod_version}"
displayName="LAN World Plug-n-Play"
#updateJSONURL=""
displayURL="https://github.com/satxm/mcwifipnp"
logoFile="mcwifipnp.png"
authors="Satxm, Rikka0w0"
description='''
Provides a better UI than the vanilla Minecraft \"Open to LAN\" screen, which now also:
1. Allows for a port customization
2. Allows a user to disable the online mode, so that unauthenticated players can also join.
3. UPnP support.
'''

[[dependencies.mcwifipnp]]
  modId="forge"
  mandatory=true
  versionRange="${forge_version_range}"
  ordering="NONE"
  side="CLIENT"

[[dependencies.mcwifipnp]]
  modId="minecraft"
  mandatory=true
  versionRange="[${minecraft_version_min}, ${minecraft_version_max})"
  ordering="NONE"
  side="CLIENT"
