org.gradle.jvmargs = -Xmx4G
org.gradle.daemon = false
org.gradle.configuration-cache=false
org.gradle.debug = false

# Mod Properties
mod_id = mcwifipnp
mod_version = 2.0.8
mod_group_id = io.github.satxm.mcwifipnp

# The Minecraft version in the development environment
minecraft_version = 26.1.2

# Fabric Properties on https://fabricmc.net/develop/
fabric_loader_version = 0.19.3
fabric_api_version = 0.155.2+26.1.2
fabric_loom_version=1.17+

# Forge Properties on https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
forge_version = 64.1.0

# NeoForge Properties on https://maven.neoforged.net/api/maven/versions/releases/net/neoforged/neoforge
neo_version = 26.1.2.100

# Mod Config
# Minecraft
# The minimum minecraft version (inclusive) to run this Mod
minecraft_version_min=26
# The maximum minecraft version (exclusive) to run this Mod
minecraft_version_max=26.2

# Fabric
fabric_version_range = *
fabric_loader_version_range = >=0.18.4

# Forge
forge_version_range = [62,)
forge_loader_version_range = [62,)

# NeoForge
neo_version_range = [26.1.0.0-beta,)
neo_loader_version_range = [2,)

# Resource Pack
pack_format_number = 101.1
